### ISSUE TITLE
这期的练习咋没有题目...

### ISSUE THREAD

**Issue by qinsJs** [hencoder/PracticeDraw4#3]
为啥一上来就是代码...

题目 （注释） 咋不见了- -

难道是朱老师太忙了吗？

**Comment by rengwuxian** [comment]
哦有吗？不记得了……可能是忘了吧😂

2017年8月15日 14:56，"WardenAndroid" <notifications@github.com>写道：

**Comment by qinsJs** [comment]
有的有的，我还大吃了一惊。  
我最开始还以为我自己 clone 有问题，还专门跑去看了一番。  
然后发现真的是 朱老师 没有写- -
