### ISSUE TITLE
糊臉修正的Sample也沒有修正

### ISSUE THREAD

**Issue by siralam** [hencoder/PracticeDraw4#5]
如題，糊臉修正上和下是一樣的～

看了代碼，Sample那裡有準備Z的量，但在onDraw沒有使用

**Comment by siralam** [comment]
不好意思，原來是效果太不明顯沒注意到… 建議newZ調高一點哦！

**Comment by rengwuxian** [comment]
是有这个问题，不过修正得太明显就会失去美观性了。另外，糊脸修正算法是对设备的像素密度兼容的，而「糊脸」效果本身是和像素密度相关，~~像素越小~~像素越大的手机上，未修正的糊脸效果越明显，所以其实也不好控制「一定」在所有测试设备上都能清楚看到修正，只能保证在修正之后在任何设备上都显示正常。

> 上面说错了，应该是像素越大的手机上，未修正的糊脸效果越明显。因为同样物理尺寸的内容所占的像素数越大，就会导致糊脸更加明显。
